apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.name" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
{{- with .Values.api }}
    api:
{{ . | toYaml | indent 6 }}
{{- end }}
{{- with .Values.database }}
    database:
{{ . | toYaml | indent 6 }}
{{- end }}
{{- with .Values.plugins }}
    plugins:
{{ . | toYaml | indent 6 }}
{{- end }}
