apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "gateway.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gateway.name" . }}
      annotations:
        checksum/config: {{ printf "%s%s%s" (.Values.api | toYaml) (.Values.database | toYaml) (.Values.plugins | toYaml) | sha256sum }}
    spec:
      serviceAccountName: "tailscale"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - start
            - --config
            - /etc/gateway/config.yaml
            - --addr
            - ":{{ .Values.service.port }}"
            - --servers
            - https://{{ include "gateway.name" . }}.{{ .Values.service.domainName }}:{{ .Values.service.publicPort }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/gateway
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "gateway.name" . }}-config