apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    edge-proxy.altinity.com/port-mapping: {{ .Values.service.publicPort }}:tls-to-tcp:{{ .Values.service.port }}
    edge-proxy.altinity.com/tls-server-name: {{ include "gateway.name" . }}.{{ .Values.service.domainName }}
  labels:
    app: {{ include "gateway.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "gateway.name" . }} 
