# Example values for altinity-mcp with JWE authentication enabled
# This configuration is equivalent to running with:
# --allow-jwe-auth --jwe-encryption-key=test-encryption-key --transport=http --port=8080 --log-level=debug --read-only

image:
  tag: "main"
  pullPolicy: Always

service:
  annotations:
    edge-proxy.altinity.com/port-mapping: 443:tls-to-tcp:8080
    edge-proxy.altinity.com/tls-server-name: mcp-github-jwt.altinity-skaeser-playground.dev.altinity.cloud

config:
  reload_time: 120
  clickhouse:
    read_only: true
  
  server:
    openapi:
      enabled: true
      tls: true
    transport: "sse"
    jwe:
      enabled: true
      encryption_key: "test-encryption-key"
  
  logging:
    level: "debug"
