# Example values for altinity-mcp with JWT authentication enabled
# This configuration is equivalent to running with:
# -allow-jwt-auth --jwt-secret-key=test-secret-key --transport=sse --port=8080 --log-level=debug --read-only

image:
  tag: "master"

service:
  annotations:
    edge-proxy.altinity.com/port-mapping: 443:tls-to-tcp:8080
    edge-proxy.altinity.com/tls-server-name: mcp-github-jwt.altinity-skaeser-playground.dev.altinity.cloud

config:
  clickhouse:
    readOnly: true
  
  server:
    transport: "sse"
    jwt:
      enabled: true
      secretKey: "test-secret-key"
  
  logging:
    level: "debug"
