# Example values for altinity-mcp with JWT authentication enabled
# This configuration is equivalent to running with:
# --allow-jwt-auth --jwt-secret-key=test-secret-key --transport=http --port=8080 --log-level=debug --read-only

image:
  tag: "main"
  pullPolicy: Always

service:
  annotations:
    edge-proxy.altinity.com/port-mapping: 443:tls-to-tcp:8080
    edge-proxy.altinity.com/tls-server-name: mcp-github-jwt.altinity-skaeser-playground.dev.altinity.cloud

config:
  clickhouse:
    read_only: true
  
  server:
    transport: "http"
    jwt:
      enabled: true
      secret_key: "test-secret-key"
  
  logging:
    level: "debug"
