image:
  repository: ghcr.io/altinity/altinity-mcp/gateway
  tag: "main"

service:
  type: ClusterIP
  port: 8090
  publicPort: 443
  domainName: altinity-skaeser-playground.dev.altinity.cloud

api:
  name: "github"
  description: "GitHub github_eventsset from github.demo.altinity.cloud"
  version: "2025-06-12"

database:
  type: clickhouse
  connection: clickhouse://github.demo.altinity.cloud:9440/default?username=demo&password=demo&secure=true

plugins:
# use --set plugins.oauth.client_id=XXX,plugins.oauth.client_secret=YYYY during `helm upgrade` for properly install
  oauth:
    client_registration:
      enabled: true
    issuer_url: https://mcp-github-oauth.altinity-skaeser-playground.dev.altinity.cloud
    provider: auth0
    provider_auth_url: https://altinity.auth0.com/authorize
    provider_token_url: https://altinity.auth0.com/oauth/token
    scopes:
    - openid
    - profile
    - email
    user_info_url: https://altinity.auth0.com/userinfo

#    provider: "google"
#    scopes:
#      - "https://www.googleapis.com/auth/userinfo.profile"
#      - "https://www.googleapis.com/auth/userinfo.email"
