image:
  repository: ghcr.io/altinity/altinity-mcp/gateway #ghcr.io/centralmind/gateway
  tag: "latest"

service:
  type: ClusterIP
  port: 8090
  publicPort: 443
  domainName: demo.altinity.cloud

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi



