apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "altinity-mcp.fullname" . }}
  labels:
    {{- include "altinity-mcp.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.config | toJson | nindent 4 }}
