apiVersion: v1
kind: Secret
metadata:
  name: {{ include "altinity-mcp.fullname" . }}
  labels:
    {{- include "altinity-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: {{ .Values.config | toYaml | quote }}
