name: Build Gateway

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/gateway

jobs:
  build-and-push-platforms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone gateway repository
      run: |
        git clone --branch add_cors_to_sse https://github.com/Slach/gateway.git /tmp/gateway
        # git clone https://github.com/centralmind/gateway.git /tmp/gateway

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build binary for ${{ matrix.platform }}
      run: |
        cd /tmp/gateway
        CGO_ENABLED=1 GOOS=linux GOARCH=${{ matrix.platform }} go build -o gateway .

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push platform image
      run: |
        cd /tmp/gateway
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        docker buildx build --platform linux/${{ matrix.platform }} --push -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.platform }}-${SHORT_SHA} .

  create-multiplatform-manifest:
    needs: build-and-push-platforms
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag,pattern={{version}}
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

    - name: Create and push multiplatform manifest
      run: |
        # Create and push multiplatform manifest
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        for tag in ${{ steps.meta.outputs.tags }}; do
          docker buildx imagetools create \
            --tag $tag \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64-${SHORT_SHA} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64-${SHORT_SHA}
        done
